
  <nav>
    <div class="topnav" id="myTopnav">    
        <a href="../index.php">Accueil</a> 
        
        <?php if(isset($_SESSION['user'])) : ?>
            
            <a class="link" href="account.php">Mon compte</a>
            <a class="link" href="myPost.php">Voir mes posts</a>
            
            <?php if ($_SESSION['user']['role'] == "admin"): ?>
            
            <a class="link" href="allUsers.php">Gestion des membres</a>
            <a class="link" href="dashboard.php">Gestion des posts</a>
            <a class="link" href="messages.php">Gestion des messages</a>
            
            <?php endif; ?>
            
            <?php if ($_SESSION['user']['role'] !== "admin") : ?>
            <a class="link" href="contact.php">Contact</a>  
            <?php endif; ?>
            
            
            <a class="link" href="deconnexion.php">Déconnexion</a>
            
            <?php else:?>
            
            <a class="link" href="inscription.php#inscription">Inscription</a>
            <a class="link" href="connexion.php#connexion">Connexion</a>
            <a class="link" href="contact.php">Contact</a>
            
            
        <?php endif;?>
        
      <a href="javascript:void(0);" class="burger" onclick="myFunction()">
        <i class="fa fa-bars"></i>
      </a>
    </div>
  </nav>




